/* tslint:disable */
/* eslint-disable */
/**
 * Todo API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PostTasks
 */
export interface PostTasks {
    /**
     * 
     * @type {string}
     * @memberof PostTasks
     */
    title: string;
}

/**
 * Check if a given object implements the PostTasks interface.
 */
export function instanceOfPostTasks(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "title" in value;

    return isInstance;
}

export function PostTasksFromJSON(json: any): PostTasks {
    return PostTasksFromJSONTyped(json, false);
}

export function PostTasksFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostTasks {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'title': json['title'],
    };
}

export function PostTasksToJSON(value?: PostTasks | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'title': value.title,
    };
}

